name: Build and Deploy
on: push

jobs:
  build:
    name: Build Binary
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install Git Bash
      uses: git-for-windows/installer@v1
      with:
        version: 'latest'
    - name: Build
      shell: bash
      run: ./release.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebGAL_Terre.exe
        path: ./release/WebGAL_Terre.exe
